---
spring:
  profiles: local

  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true

logging:
  level:
    org:
      hibernate: info

---
spring:
  profiles: prod

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jboard
      username: root
      password:
